ANCHO = 800
ALTO = 600
FPS = 60

TITULO_VENTANA = "Menú Principal - Aulas Jugadas"

# --- Rutas de assets ---
RUTA_IMAGENES = "assets/images/"
RUTA_SONIDOS = "assets/sounds/"

IMG_FONDO_AULA = RUTA_IMAGENES + "image_01.jpeg"
IMG_FONDO_SUBMENU_COMPUTACION = RUTA_IMAGENES + "image_02.jpeg"
IMG_PLAY = RUTA_IMAGENES + "play.png"
IMG_PAUSE = RUTA_IMAGENES + "pause.png"
IMG_SALIR = RUTA_IMAGENES + "logout.png"
IMG_CAJA = RUTA_IMAGENES + "caja.png"
IMG_FONDO_HARDWARE_SOFTWARE = RUTA_IMAGENES + "fondohardsoft.jpeg"

SONIDO_MUSICA_FONDO = RUTA_SONIDOS + "Pizarra_de_ideas.wav"
SONIDO_MUSICA_SUBMENU_COMPUTACION = RUTA_SONIDOS + "aulas_jugadas_2.mpeg"
SONIDO_CLIC = RUTA_SONIDOS + "click_videojuego.wav"

VOLUMEN_MUSICA = 0.3

# --- Colores ---
COLOR_BLANCO = (255, 255, 255)
COLOR_NUMEROS = (50, 150, 50)
COLOR_LECTURA = (150, 50, 50)
COLOR_GEOGRAFIA = (50, 150, 220)
COLOR_COMPUTACION = (70, 70, 70)
